
package servicio;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "usuario", targetNamespace = "http://servicio/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Usuario {


    /**
     * 
     * @param id
     * @return
     *     returns servicio.UsuarioResponse
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuario", targetNamespace = "http://servicio/", className = "servicio.ObtenerUsuario")
    @ResponseWrapper(localName = "obtenerUsuarioResponse", targetNamespace = "http://servicio/", className = "servicio.ObtenerUsuarioResponse")
    @Action(input = "http://servicio/usuario/obtenerUsuarioRequest", output = "http://servicio/usuario/obtenerUsuarioResponse")
    public UsuarioResponse obtenerUsuario(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<servicio.UsuarioResponse>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuarios", targetNamespace = "http://servicio/", className = "servicio.ObtenerUsuarios")
    @ResponseWrapper(localName = "obtenerUsuariosResponse", targetNamespace = "http://servicio/", className = "servicio.ObtenerUsuariosResponse")
    @Action(input = "http://servicio/usuario/obtenerUsuariosRequest", output = "http://servicio/usuario/obtenerUsuariosResponse")
    public List<UsuarioResponse> obtenerUsuarios();

}
